#!/usr/bin/env python
#
# vi:set et ai sw=4 sts=4 ts=4: */
# -
# Copyright (c) 2010 Jannis Pohlmann <jannis@xfce.org>
# 
# This program is free software; you can redistribute it and/or 
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 2 of 
# the License, or (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the 
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public 
# License along with this program; if not, write to the Free 
# Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
# Boston, MA 02110-1301, USA.


import sys
import os
import pygtk
pygtk.require('2.0')
import gtk


def get_search_path(pathname):
    return os.path.join(pathname, "app-time-tracker")


if __name__ == "__main__":
    # add the app time tracker directory to the python search path
    sys.path += map(get_search_path, sys.path)

    # initialize the GLib threading system
    gtk.gdk.threads_init()

    # create the tray icon
    from ui.main import AppTimeTrackerApplication
    application = AppTimeTrackerApplication()
    application.run()

    # run the application
    gtk.main()
